import Head from "next/head";
import Navbar from "../components/Navbar";
import PageContent from "../components/PageContent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <PageContent />
    </div>
  );
}
