import Head from "next/head";
import Footer from "../components/Footer";
import { Media } from "../components/Media";
import Navbar from "../components/Navbar";
import PageContent from "../components/PageContent";

export default function Home({ media }) {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <PageContent media={media} />
      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  return {
    props: {
      media: Media,
    },
  };
};
