import Head from "next/head";
import { Messenger } from "../components/Icons";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>This is Instagram</h1>
        <p>
          <Messenger />
        </p>
      </main>
    </div>
  );
}
